package me.shark0822.combatSystem.stats;

public enum StatType {
    DAMAGE_REDUCTION,
    REDUCTION_IGNORED,

    TAKEN_DAMAGE_INCREASE,
    TAKEN_DAMAGE_INCREASE_FLAME,
    TAKEN_DAMAGE_INCREASE_FROST,
    TAKEN_DAMAGE_INCREASE_GALE,
    TAKEN_DAMAGE_INCREASE_ELECTRIC,
    TAKEN_DAMAGE_INCREASE_DARKNESS,
    TAKEN_DAMAGE_INCREASE_DIVINE,

    DAMAGE_INCREASE,
    DAMAGE_INCREASE_FLAME,
    DAMAGE_INCREASE_FROST,
    DAMAGE_INCREASE_GALE,
    DAMAGE_INCREASE_ELECTRIC,
    DAMAGE_INCREASE_DARKNESS,
    DAMAGE_INCREASE_DIVINE
}
